# FAÇA UM PROGRAMA QUE PEDE PARA O USUARIO DIGITAR UMA SENHA E VERIFICAR SE É UMA SENHA FORTE
# REGRA: UMA SENHA FORTE TEM QUE CONTER NO MINIMO
# 1 LETRA MAIUSCULA
# 1 LETRA MINUSCULA
# 1 CARACTER ESPECIAL
# 1 NUMERO
# 8 DIGITOS

